inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/unit/**/*'

Metrics/LineLength:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
