language: ruby
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - ruby-head
  - jruby-1.7.27
  - jruby-9.2.7.0
  - rbx-3.107
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-1.7.27
    - rvm: jruby-9.2.7.0
    - rvm: rbx-3.107
